apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-verification-bot
  labels:
    app: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot
        image: your-registry/telegram-verification-bot:latest
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: telegram-token
        - name: ADMIN_ID
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: admin-id
        - name: SPREADSHEET_ID
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: spreadsheet-id
        - name: CREDENTIALS_PATH
          value: "/app/credentials.json"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: google-credentials
          mountPath: /app/credentials.json
          subPath: credentials.json
          readOnly: true
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      restartPolicy: Always

---
apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
type: Opaque
stringData:
  telegram-token: "YOUR_TELEGRAM_TOKEN"
  admin-id: "YOUR_ADMIN_ID"
  spreadsheet-id: "YOUR_SPREADSHEET_ID"

---
apiVersion: v1
kind: Secret
metadata:
  name: google-credentials
type: Opaque
data:
  credentials.json: # Base64 encoded credentials.json content
